---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: monitoring
spec:
  interval: 12h
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    updater:
      enabled: false
    admissionController:
      enabled: false
