---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Vienna"
  KUBE_VIP_ADDR: "192.168.20.254"
  METALLB_LB_RANGE: "192.168.20.231-192.168.20.240"
  METALLB_K8S_GATEWAY_ADDR: "192.168.20.220"
  METALLB_INGRESS_ADDR: "192.168.20.221"
