---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/infrastructure/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/infrastructure/terraform"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

includes:
  precommit: .taskfiles/PrecommitTasks.yml
  ansible: .taskfiles/AnsibleTasks.yml
  flux: .taskfiles/FluxTasks.yml
  terraform: .taskfiles/TerraformTasks.yml
  cloudflare: .taskfiles/Cloudflare.yml

tasks:
  default:
    silent: true
    cmds:
      - task -l
