---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.4.1
    env:
      TZ: "${TIMEZONE}"
      PORT: &port 5055
      LOG_LEVEL: warn
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:eye-circle
        hosts:
          - host: &host "jellyseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyseerr-tls
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /app/config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-path
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1500Mi
