---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.3.6

    service:
      main:
        ports:
          http:
            port: 8123
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
