apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:uML3HCT3dLmOCXJ0oC1hifkv+SxJugylUdm2Qcut5Sc=,iv:Zr0Iy4H2U4Vb7Fm02IcI2/DnsUdmapeFPgrwGDZGJJg=,tag:TTTR7hOvOYV8DuMAH8sQcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150agqmrmg07t4quc4u5t3hyer86qp7eqcjgz3pawlhtwnevlgesqvl2n3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZW5rbVh4WmpJN0FDN09P
            K2hjS2V0cStNenI4Z1M2dzAvb2tidytpcUNJCndBbFIrZ0liZ3oxYWdHaWhIVVdq
            YWc1SUdZYzFNRnV6Tk1zQTR2Zks1WUEKLS0tIDZLMzFwWlZTTjExOXZsTlY1SjE0
            MTFDdE1BN21TYzh4UlZmQTd2c1daMEUKpYyFGVBu8GSxVHGDb66WqPgKWsyia49A
            97f5pc6IomBXz4RgVZVYe396yob34IhPTprQa76NfJwPSs6HHutvQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T19:35:57Z"
    mac: ENC[AES256_GCM,data:0p6cDKLATi7H1Sx7QokMTZh86uZdRYRyJFMGAV//0zNhgeUiqfGZSQ0pS6thCuXZoBPikvuvO7uVr0vuKiIY8Y09Zw5ZlZWmUtkKjKGIfbV088PbhX5s2hyUmn67cbYyb/mIJKjP799mDLxzPLw+Mglh/mXZrmERo5SDmTpte2k=,iv:h9C2/8zHOTrizaix36epeQnkiX0xMCZ6764VvjJUyNc=,tag:1M8u8c24OuZUj34UCbofBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
