---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./hajimari.yaml
  - ./jetstack.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./kubernetes-dashboard.yaml
  - ./weave-gitops.yaml
