---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      version: 1.3.2
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: '${METALLB_MOSQUITTO_ADDR}'
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            primary: true
            port: 1883
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous true
            persistence true
            persistence_location /data
            autosave_interval 1800
            connection_messages false
    persistence:
      data:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: "1Gi"
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 150Mi
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 512Mi
        storageClass: local-path
