# yamllint disable
# cloud: |-
#     [default]
#     aws_access_key_id=
#     aws_secret_access_key=
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-minio-credentials
    namespace: kube-system
stringData:
    cloud: ENC[AES256_GCM,data:TJsyZT5vccdsnGam2E4v/yOyWMEfkRN2AGJVWjBz4hCujNVMMrE3JLcC64CuYjDjql0XZe8YzvT2pmnqgRGtD6lQSsdgC9CRW1r5iEvieYkolFATy6qOxeWyHDCS4A==,iv:jNQZgDif3msrIMujaKWdZk1jEyUkoB8hENDy7wZBg7g=,tag:KpFGtOAriwqVAsK4rcLNIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150agqmrmg07t4quc4u5t3hyer86qp7eqcjgz3pawlhtwnevlgesqvl2n3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaU4zU2l4UUV4bnFkM0tz
            eU9CS1MybjFWd3dhNmdRalp3ME9lQzUyQ0MwCjl4T29qcjJUeDc0cjkxTm1sa0Nw
            aURIbytDRkZ4bWFCWHZ5Y3R3UzIyZ1EKLS0tIDd4MURQMitQYXRMRDM5U01tTjdz
            T3B1cEhJREk0SzBhMFdtcXJWNzRPWFEK/jsrwx4sFG9iVqXANP/R03aHkHGchLhw
            wvvCTE/GJwbT+qQPI2teeleu+dYYyCAI+4eGP7BILjj9ruNN6TT0/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T14:55:48Z"
    mac: ENC[AES256_GCM,data:9YyC5MpBC+L0N2ZC82YHO9AilJ3cdVpyphQWeW2fjbuzValYx4yofDF7NaaozQqvd0nfRNLWYhbvgE1ygPwcP7qKgo+MPbIN+wBBeuOh6Jnu29MYba5KU4QFUK8hsFvD0ujC6nKQXfTBMWRXBO6Qo+txLkpQLLYNd6wS7llsq70=,iv:uOtt1923O7NJg6/MFEcYzqj/abqJjplvLH/+0rwhTag=,tag:2PlNHhFRTwFGYgkoLDPYzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
