cloudflare_email: ENC[AES256_GCM,data:Sl79eDBfL/6YnICa5xxQyIuYNg==,iv:R45pXvuKkNn/Xg9gyfVdOm1ITAB8BLs5WCV8L2Uqf+o=,tag:dnu+E7tigHlIZJgD2KlQUw==,type:str]
cloudflare_apikey: ENC[AES256_GCM,data:P/0XRFgr1IOrzt7SmpcVUGlb2L+2CqIaKPOyxnvkG/WCIfBAZw==,iv:N898Xq2frF5j1Lh4n4mqF2YXsc+cIGsi+QI9IvIwhNI=,tag:Xvt70oUhojmQ+nvKalc+3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150agqmrmg07t4quc4u5t3hyer86qp7eqcjgz3pawlhtwnevlgesqvl2n3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ2xVa1NVZ2EzeXVxVVB5
            ZkNEQzhqOEFQby9FL0hEY0ZhdHY0UDBBTGdRCklza2NJbUtKN2pIR3c5cWVaMWhS
            NVhSZHdEL0NnY1FGaER2YkVSd1dtY2MKLS0tIEdmdUtlVU8zckVEQ3FoVzl3Wnhq
            UVFyN1hsTTAzcEwyYWU0c2drM1VRbnMKGN/iq/dToVqxQFMS8fTxtGwEzB20OhTI
            mYl+qOxVPBYO4bMGpID/7DJljFHJtn1fGTNZNOKVRNBUDmwtuBFiyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-31T15:57:20Z"
    mac: ENC[AES256_GCM,data:cNTPoJfEtNbhOZ5Vw09SZlBGW7ugrwDfNHAkMSmPrNWGxP7r5Oa5L+RlU9bfokjAxj9h7py+fWMjXsiefMEP+JFxvtVGxDTErevbC9w207KNV9ZMIOTsaCh/oabf0P37jT/wdrPdi9mH0QI+hDU4bJCHe2mSbKBtrhwy4N0/sSs=,iv:+iKQV5axfsjFcHOYqCwJb5wgwDis1YqQQuAdn+DvymU=,tag:/1Ve8UAbza4Gyx2pcWe01A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
