---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 12h
  chart:
    spec:
      chart: goldilocks
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    vpa:
      enabled: false
    metrics-server:
      enabled: false
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          coredns.io/hostname: &host "goldilocks.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
        hosts:
          - host: *host
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: goldilocks-tls
    controller:
      rbac:
        extraRules:
          - apiGroups:
              - batch
            resources:
              - '*'
            verbs:
              - get
              - list
              - watch
