---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-weave-gitops
  namespace: flux-system
spec:
  path: ./kubernetes/apps/base/flux-system/weave-gitops/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: weave-gitops
      namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
