apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:qL311jgFn8sUr6K9xJaq1akiaqYnoU5PVt603MgJz+mr45kCgA==,iv:BUXe3yQe7ccZcyTlWqND98HqBfTyiJXGIWhaHi0p4yo=,tag:CDULrgrwzQRDmGCBHB0q1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150agqmrmg07t4quc4u5t3hyer86qp7eqcjgz3pawlhtwnevlgesqvl2n3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aWc3Uzl6Qi8xZjMzYVlC
            dzVnV1hwb0l2UjBUUE41QkFZQi9ZcU9nNHh3ClpJcUYvMWRtbmR6YUZpNWFWY3p0
            RHNOc3I1OVNKeWhGWnpIWENhUWYyUkkKLS0tIEtsR0h0eVdCVUxFbjlSbVlJNjJF
            UGRHRTlJclNHeHNoTGVUQklJeUVvYVkKNuhAgZRKwF99wadJjYbgzVBdWFpyX61K
            IppDIS7bRrYKxm8TFk4SKe0DeTjQnDGKjN9/+R+3CitikdEnJv9Xsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T16:32:06Z"
    mac: ENC[AES256_GCM,data:ciCCuLkRQCYwYco+iltSAX+zHwqEljkMgl7KIC3TpVSrlub+TzSl0H8P7wUMYuSebtPa8v2sQsLQ8AiUgrbOnEQhdIyAxekE0JjZ5OLEvFTh4M90N5/gAPmaHN97YktcNNwgYXOeQX0Nx62csp0UtQWoHNxPZHVFS8AdzeDim7A=,iv:sjlFHh1kgpyW5ISkxli+aXZEL5BbWLIqB+69QTV08JI=,tag:eFStFMaB+YHU0CHRmZm4NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
