---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.20
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: "traefik"
    #     annotations:
    #       coredns.io/hostname: &host "gitops.${SECRET_DOMAIN}"
    #       cert-manager.io/cluster-issuer: letsencrypt
    #       traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #       hajimari.io/enable: "true"
    #     hosts:
    #       - host: *host
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host
    #         secretName: weave-gitops-tls
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash
