---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./cluster.yaml
  # TODO: add backup
  # TODO: add prometheus rule
  - ./service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudnative-pg-cluster
      app.kubernetes.io/instance: cloudnative-pg-cluster
      app.kubernetes.io/part-of: cloudnative-pg
