---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.12.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    master:
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      resources:
        requests:
          cpu: 5m
          memory: 64M
        limits:
          memory: 64M
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/master"
                    operator: In
                    values: [""]
    worker:
      resources:
        requests:
          cpu: 5m
          memory: 64M
        limits:
          memory: 64M
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          custom:
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
