kind: ENC[AES256_GCM,data:qXJlIoSp,iv:hSsF86WuOkb1VRjX0vmTvDlW6TdCQHKddzLKCQbs91w=,tag:lOqzm/0UDzWbIlsEd6FsTw==,type:str]
ansible_user: ENC[AES256_GCM,data:gR4Q9RS2,iv:sPewIVsG+ZYlOOTVWMufzQQ8EQf0PUCaX0gwAH8ZKRc=,tag:FEHg+fdhqDmTv/oiZ49G/A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:pU8saGb+,iv:WWY8xkC0u6dm1QrqV7pISuQMW8hgLQjvO81RgnFivd4=,tag:qUd3HRiLaQ2W4ImrqcZGRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150agqmrmg07t4quc4u5t3hyer86qp7eqcjgz3pawlhtwnevlgesqvl2n3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUG5ILzlWaG80RVNJS2VQ
            ZThBeGdiRjBOY3I5WWhMa0JsOTRkcDV5Ym5JCi83R050c0lUaEdNMlNMdTZhZUNP
            UEZtcTJqZ2JOZU9tMU8rTTNralg4TzgKLS0tIDE4UWdkQjBUSXI3SjNuTmN0a1Vh
            SUpQa0NYQ21SdjZ5eGZiaVNOb3pQWTgK6u0ZfsghAO9BaNxnHevUnM1yGzHbQDxp
            ZlrxUOELX+ObsLuPFZIvWGeyH8zH04E5s/OYRkh9pHvFDJhhn/7xPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T21:40:15Z"
    mac: ENC[AES256_GCM,data:tnlxf6qqE9IwiY3sPHy8K/QhGSUtBVYIM+0DmoEea4Wqf+WTj4qP6DZd0HZ74TmG4Jq6gbIbWAsofeBSGqZhZ0aqzWQvOswHvvSDpn7D4FvYqVyXvRcVAjowZeYoGOXVCv1t0ZnSoCrkv/6E6YZiAXgTuNcIsPuA4Ezi435k2hg=,iv:I1/czLhnjwiQjSwYE+8xsXN4gebOWhZhKNE1y789pmo=,tag:RJWPHKLGunzngFlW+O1unw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
